version: "2"
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:5000/api
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8082:8080
