version: "2"
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  backend:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000
  adminer:
    image: adminer
    ports:
      - 8082:8080
